server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 10
  port: 8080

#  servlet:
#    context-path: /

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/emall?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  resources:
        static-locations: classpath:/static/, classpath:/html/, classpath:/mall/, classpath:/upload
        cache:
          period: 0

  mvc:
    static-path-pattern: /**

#  thymeleaf:
#    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml